name: PR Version Check

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  enforce-version-update:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
